# [mode]: prod

log:
  log_level: info
  encoding: json # json or console
  log_filename: "./storage/logs/gotoy.log" # log 文件名
  max_backups: 30 # 日志文件最多保存多少个备份
  max_age: 7 # 文件最多保存多少天
  max_size: 64 # 每个日志文件保存的最大尺寸,单位：M
  compress: true # 是否压缩
