// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"yafgo/yafgo-layout/internal/server"
)

// Injectors from app_wire.go:

func newApp(envConf string) (*application, func(), error) {
	config := NewYCfg(envConf)
	logger := NewYLog(config)
	webService := server.NewWebService(logger, config)
	application := newApplication(logger, config, webService)
	return application, func() {
	}, nil
}

// app_wire.go:

var yCfgSet = wire.NewSet(NewYCfg)

var yLogSet = wire.NewSet(NewYLog)
